project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true
base_path: ./resources/

files:
  - source: locales-sources/*.ftl
    translation: locales/%locale%/%original_file_name%
